version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: codeartnode
    restart: unless-stopped
    #ports:
    #  - '8090:8090' 
    networks:
      - nginxdockerssl_app-network

volumes:
  database:

networks:
  nginxdockerssl_app-network:
    external: true 


