export const API_REQUEST = 'API_REQUEST';
export const API_RESPONSE = 'API_RESPONSE';
export const API_RESET = 'API_RESET';
export const APPLICATION_LOADED = 'APPLICATION_LOADED';
export const INPUT_BUTTON_ON = 'INPUT_BUTTON_ON';
export const INPUT_BUTTON_OFF = 'INPUT_BUTTON_OFF';



