export const REQUEST_OUTPUT_VALUES = 'REQUEST_OUTPUT_VALUES';
export const REQUESTED_OUTPUT_VALUE_RESPONSE = 'REQUESTED_OUTPUT_VALUE_RESPONSE';
export const INPUT_BUTTON_ON = 'INPUT_BUTTON_ON';
export const INPUT_BUTTON_OFF = 'INPUT_BUTTON_OFF';
export const GET_GAME_KEYS = 'GET_GAME_KEYS';
export const GAME_KEYS_RESPONSE = 'GAME_KEYS_RESPONSE';
export const SET_GAME_VALUE = 'SET_GAME_VALUE';
export const TURN_INPUT_OFF = 'TURN_INPUT_OFF';
export const TURN_INPUT_ON = 'TURN_INPUT_ON';


